# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finterest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='address_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_id', to='finterest_app.Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
