# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finterest_app', '0003_auto_20180724_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='favorite_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_image',
        ),
    ]
