# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finterest_app', '0004_auto_20180725_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='favorite_image',
            field=models.ImageField(blank=True, upload_to='favorite_image'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
